apiVersion: v1
kind: Service
metadata:
  name: alertmappingapi
spec:
  type: NodePort
  selector:
    app: alertmappingapi
  ports:
  - port: 5000 
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmappingapi
  namespace: keep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmappingapi
  template:
    metadata:
      labels:
        app: alertmappingapi
    spec:
      containers:
      - name: alertmappingapi
        image: docker.io/kavindukalinga/servicedepend:1.0.0 # docker pull kavindukalinga/servicedepend:1.0.0
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000