apiVersion: v1
kind: Service
metadata:
  name: getconnectionsdirectly
spec:
  type: NodePort
  selector:
    app: getconnectionsdirectly
  ports:
  - port: 5000 
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getconnectionsdirectly
  namespace: keep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getconnectionsdirectly
  template:
    metadata:
      labels:
        app: getconnectionsdirectly
    spec:
      containers:
      - name: getconnectionsdirectly
        image: docker.io/kavindukalinga/getconnectionsdirectly
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000